/**
 * Pure event logic (no Astro imports) so it can be unit tested:
 * recurring-series expansion, occurrence overrides, sorting and upcoming/past partitioning.
 */
import type { z } from 'astro/zod';
import type { eventSchema, seriesSchema, EventStatus } from './schemas';
import { DEFAULT_TZ, addDays, daysInMonth, parseLocal, weekdayOf, zonedToUtc, WEEKDAYS, dateInZone } from './time';

type AnyImage = unknown;
export type EventData = z.infer<ReturnType<typeof eventSchema>>;
export type SeriesData = z.infer<ReturnType<typeof seriesSchema>>;

export interface RawEvent {
  id: string;
  data: EventData;
}
export interface RawSeries {
  id: string;
  data: SeriesData;
}

/** Detail fields that can be inherited from a series and overridden per occurrence. */
export const DETAIL_KEYS = [
  'host',
  'organizer',
  'infoUrl',
  'sourceName',
  'sourceUrl',
  'cadence',
  'summary',
  'doorsTime',
  'lessonStartTime',
  'danceStartTime',
  'danceEndTime',
  'venue',
  'address',
  'city',
  'state',
  'postalCode',
  'latitude',
  'longitude',
  'directionsUrl',
  'instructorNames',
  'djNames',
  'bandName',
  'danceStyles',
  'eventTypes',
  'experienceLevel',
  'partnerRequired',
  'beginnerFriendly',
  'admissionMember',
  'admissionNonMember',
  'admissionStudent',
  'admissionNotes',
  'registrationUrl',
  'registrationRequired',
  'capacityNotes',
  'featuredImage',
  'featuredImageAlt',
  'gallery',
  'sponsor',
  'contactName',
  'contactEmail',
  'contactPhone',
  'facebookEventUrl',
  'seoTitle',
  'seoDescription',
  'lastUpdated',
] as const;
export type DetailKey = (typeof DETAIL_KEYS)[number];
export type EventDetails = { [K in DetailKey]?: EventData[K] };

export type SourceKind = 'event' | 'series-occurrence' | 'series-override';

export interface Occurrence {
  /** URL segment, e.g. "2026-10-06-tuesday-night-swing". Stable for the life of the event. */
  slug: string;
  title: string;
  status: EventStatus;
  /** status adjusted for time: scheduled/soldOut events that have ended become "completed". */
  effectiveStatus: EventStatus;
  date: string;
  timeTba: boolean;
  startLocal: string;
  endLocal: string;
  start: Date;
  end: Date;
  timezone: string;
  featured: boolean;
  cancelledMessage?: string | undefined;
  postponedTo?: string | undefined;
  details: EventDetails;
  source: { kind: SourceKind; eventId?: string; seriesId?: string };
}

const isEmpty = (v: unknown) => v === undefined || v === null || v === '' || (Array.isArray(v) && v.length === 0);

/** Copy detail fields from `override` onto `base`, ignoring blank values so they inherit. */
export function mergeDetails(base: EventDetails, override: EventDetails): EventDetails {
  const out: Record<string, unknown> = { ...base };
  for (const key of DETAIL_KEYS) {
    const v = (override as Record<string, unknown>)[key];
    if (!isEmpty(v)) out[key] = v;
  }
  return out as EventDetails;
}

export function pickDetails(source: Record<string, unknown>): EventDetails {
  const out: Record<string, unknown> = {};
  for (const key of DETAIL_KEYS) if (!isEmpty(source[key])) out[key] = source[key];
  return out as EventDetails;
}

function nthWeekdayOfMonth(year: number, month: number, weekday: number, nth: number): string | null {
  const pad = (n: number) => String(n).padStart(2, '0');
  if (nth === -1) {
    const last = daysInMonth(year, month);
    for (let d = last; d > last - 7; d--) {
      const date = `${year}-${pad(month)}-${pad(d)}`;
      if (WEEKDAYS.indexOf(weekdayOf(date)) === weekday) return date;
    }
    return null;
  }
  let count = 0;
  for (let d = 1; d <= daysInMonth(year, month); d++) {
    const date = `${year}-${pad(month)}-${pad(d)}`;
    if (WEEKDAYS.indexOf(weekdayOf(date)) === weekday && ++count === nth) return date;
  }
  return null;
}

/** Dates generated by a series rule between its start date and `until` (inclusive). */
export function expandRecurrence(rule: SeriesData['recurrence'], until: string): string[] {
  const end = rule.endDate && rule.endDate < until ? rule.endDate : until;
  const except = new Set(rule.exceptDates ?? []);
  const target = WEEKDAYS.indexOf(rule.weekday);
  const dates: string[] = [];
  if (rule.frequency === 'weekly') {
    let d = rule.startDate;
    while (WEEKDAYS.indexOf(weekdayOf(d)) !== target) d = addDays(d, 1);
    for (; d <= end; d = addDays(d, 7 * rule.interval)) if (!except.has(d)) dates.push(d);
  } else {
    let [y, m] = rule.startDate.split('-').map(Number) as [number, number];
    for (let i = 0; i < 600; i++) {
      const d = nthWeekdayOfMonth(y, m, target, rule.weekOfMonth ?? 1);
      if (d && d > end) break;
      if (d && d >= rule.startDate && !except.has(d)) dates.push(d);
      m += rule.interval;
      while (m > 12) {
        m -= 12;
        y += 1;
      }
      if (`${y}-${String(m).padStart(2, '0')}-01` > end) break;
    }
  }
  return dates;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80)
    .replace(/-+$/g, '');
}
export { slugify };

/** Slug segment for a one-time event: explicit slug, else the file name without a date prefix. */
export function eventSlugPart(id: string, data: Pick<EventData, 'slug' | 'title'>): string {
  if (data.slug) return data.slug;
  const base = id.split('/').pop()!.replace(/\.md$/, '').replace(/^\d{4}-\d{2}-\d{2}-?/, '');
  return slugify(base) || slugify(data.title);
}

interface Timing {
  date: string;
  timeTba: boolean;
  startLocal: string;
  endLocal: string;
  start: Date;
  end: Date;
}

function computeTiming(
  startLocal: string,
  endLocal: string | undefined,
  danceEndTime: string | undefined,
  tz: string,
): Timing {
  const s = parseLocal(startLocal);
  if (!s.time) {
    return {
      date: s.date,
      timeTba: true,
      startLocal: s.date,
      endLocal: s.date,
      start: zonedToUtc(s.date, '00:00', tz),
      end: zonedToUtc(addDays(s.date, 1), '00:00', tz),
    };
  }
  const start = zonedToUtc(s.date, s.time, tz);
  let end: Date;
  let endStr: string;
  if (endLocal) {
    const e = parseLocal(endLocal);
    const eTime = e.time ?? '23:59';
    // A same-day end at or before the start (e.g. 8 PM to 12 AM) means the event runs past midnight.
    const eDate = e.date === s.date && e.time && eTime <= s.time ? addDays(e.date, 1) : e.date;
    endStr = `${eDate}T${eTime}`;
    end = zonedToUtc(eDate, eTime, tz);
  } else if (danceEndTime && danceEndTime > s.time) {
    endStr = `${s.date}T${danceEndTime}`;
    end = zonedToUtc(s.date, danceEndTime, tz);
  } else {
    end = new Date(start.getTime() + 3 * 3600 * 1000);
    endStr = `${dateInZone(end, tz)}T${new Intl.DateTimeFormat('en-GB', { timeZone: tz, hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(end)}`;
  }
  return { date: s.date, timeTba: false, startLocal: `${s.date}T${s.time}`, endLocal: endStr, start, end };
}

export function effectiveStatus(status: EventStatus, end: Date, now: Date): EventStatus {
  if ((status === 'scheduled' || status === 'soldOut') && end.getTime() <= now.getTime()) return 'completed';
  return status;
}

export interface ResolveOptions {
  now: Date;
  /** Include unpublished/draft entries (local preview only). */
  includeDrafts?: boolean;
}

/** Build the full list of public event occurrences from one-time events and series. */
export function resolveOccurrences(events: RawEvent[], series: RawSeries[], opts: ResolveOptions): Occurrence[] {
  const { now } = opts;
  const today = dateInZone(now, DEFAULT_TZ);
  const out: Occurrence[] = [];
  const seriesById = new Map(series.map((s) => [s.id, s]));
  const overrides = new Map<string, RawEvent>();

  for (const ev of events) {
    if (ev.data.series) {
      if (!seriesById.has(ev.data.series)) {
        throw new Error(`Event "${ev.id}" refers to unknown series "${ev.data.series}".`);
      }
      const key = `${ev.data.series}|${ev.data.occurrenceDate}`;
      if (overrides.has(key)) throw new Error(`Two entries override ${key}: "${overrides.get(key)!.id}" and "${ev.id}".`);
      overrides.set(key, ev);
    }
  }

  const visible = (published: boolean, status: EventStatus) => opts.includeDrafts || (published && status !== 'draft');

  for (const ev of events) {
    if (ev.data.series) continue;
    const d = ev.data;
    if (!visible(d.published, d.status)) continue;
    const tz = d.timezone ?? DEFAULT_TZ;
    const timing = computeTiming(d.startDateTime!, d.endDateTime, d.danceEndTime, tz);
    out.push({
      slug: `${timing.date}-${eventSlugPart(ev.id, d)}`,
      title: d.title,
      status: d.status,
      effectiveStatus: effectiveStatus(d.status, timing.end, now),
      ...timing,
      timezone: tz,
      featured: d.featured,
      cancelledMessage: d.cancelledMessage,
      postponedTo: d.postponedTo,
      details: pickDetails(d as Record<string, unknown>),
      source: { kind: 'event', eventId: ev.id },
    });
  }

  for (const s of series) {
    const sd = s.data;
    if (!sd.published) continue;
    const horizon = addDays(today, sd.recurrence.horizonWeeks * 7);
    const generated = new Set(expandRecurrence(sd.recurrence, horizon));
    const overrideDates = [...overrides.values()].filter((o) => o.data.series === s.id).map((o) => o.data.occurrenceDate!);
    const allDates = [...new Set([...generated, ...overrideDates])].sort();
    const base = pickDetails(sd as Record<string, unknown>);
    for (const date of allDates) {
      const ov = overrides.get(`${s.id}|${date}`);
      if (ov && !visible(ov.data.published, ov.data.status)) continue;
      const tz = ov?.data.timezone ?? sd.timezone ?? DEFAULT_TZ;
      const details = ov ? mergeDetails(base, pickDetails(ov.data as Record<string, unknown>)) : base;
      const startLocal = ov?.data.startDateTime ?? `${date}T${sd.startTime}`;
      const endLocal = ov?.data.endDateTime ?? (ov?.data.startDateTime ? undefined : `${date}T${details.danceEndTime ?? sd.endTime}`);
      const timing = computeTiming(startLocal, endLocal, details.danceEndTime ?? sd.endTime, tz);
      const status = ov?.data.status ?? 'scheduled';
      out.push({
        slug: `${date}-${sd.slug}`,
        title: ov?.data.title ?? sd.title,
        status,
        effectiveStatus: effectiveStatus(status, timing.end, now),
        ...timing,
        timezone: tz,
        featured: ov?.data.featured ?? false,
        cancelledMessage: ov?.data.cancelledMessage,
        postponedTo: ov?.data.postponedTo,
        details,
        source: ov ? { kind: 'series-override', seriesId: s.id, eventId: ov.id } : { kind: 'series-occurrence', seriesId: s.id },
      });
    }
  }

  const seen = new Map<string, Occurrence>();
  for (const o of out) {
    if (seen.has(o.slug)) {
      throw new Error(`Duplicate event URL "/events/${o.slug}/". Give one of the events a different title or slug.`);
    }
    seen.set(o.slug, o);
  }
  return sortOccurrences(out);
}

export function sortOccurrences<T extends Pick<Occurrence, 'start' | 'title'>>(list: T[]): T[] {
  return [...list].sort((a, b) => a.start.getTime() - b.start.getTime() || a.title.localeCompare(b.title));
}

/** Upcoming = not yet ended. Cancelled/postponed upcoming events stay visible (clearly marked). */
export function isUpcoming(o: Pick<Occurrence, 'end' | 'status'>, now: Date): boolean {
  return o.end.getTime() > now.getTime() && o.status !== 'draft' && o.status !== 'completed';
}

export function partition(list: Occurrence[], now: Date) {
  const upcoming = list.filter((o) => isUpcoming(o, now));
  const past = list.filter((o) => !isUpcoming(o, now)).reverse();
  return { upcoming, past };
}

/** Host of an occurrence. Entries without a host are SDLI events (the site's own calendar). */
export function hostOf(o: Pick<Occurrence, 'details'>): 'sdli' | 'community' {
  return o.details.host === 'community' ? 'community' : 'sdli';
}

/** Next event that is actually happening (not cancelled or postponed). Defaults to SDLI events only. */
export function nextConfirmed(list: Occurrence[], now: Date, host: 'sdli' | 'community' | 'any' = 'sdli'): Occurrence | undefined {
  return list.find(
    (o) => isUpcoming(o, now) && (o.status === 'scheduled' || o.status === 'soldOut') && (host === 'any' || hostOf(o) === host),
  );
}

/** Stable display order: SDLI events first (chronological), then community events (chronological). */
export function sdliFirst<T extends Pick<Occurrence, 'details' | 'start' | 'title'>>(list: T[]): T[] {
  const sorted = sortOccurrences(list);
  return [...sorted.filter((o) => hostOf(o) === 'sdli'), ...sorted.filter((o) => hostOf(o) === 'community')];
}

export interface AdmissionSummary {
  member?: number | undefined;
  student?: number | undefined;
  nonMember?: number | undefined;
  notes?: string | undefined;
  free: boolean;
  known: boolean;
}

export function admissionOf(d: EventDetails): AdmissionSummary {
  const member = d.admissionMember;
  const student = d.admissionStudent;
  const nonMember = d.admissionNonMember;
  const known = [member, student, nonMember].some((v) => typeof v === 'number');
  const free = known && [member, student, nonMember].every((v) => v === undefined || v === 0);
  return { member, student, nonMember, notes: d.admissionNotes, free, known };
}

export function formatPrice(n: number): string {
  return n === 0 ? 'Free' : `$${Number.isInteger(n) ? n : n.toFixed(2)}`;
}

/** Plain-language admission line, e.g. "$15 non-members, $10 members, $5 students". */
export function admissionText(a: AdmissionSummary): string {
  if (!a.known) return a.notes ?? 'Admission details to be announced';
  if (a.free) return 'Free';
  const parts: string[] = [];
  if (a.nonMember !== undefined) parts.push(`${formatPrice(a.nonMember)} non-members`);
  if (a.member !== undefined) parts.push(`${formatPrice(a.member)} members`);
  if (a.student !== undefined) parts.push(`${formatPrice(a.student)} students`);
  return parts.join(', ');
}

export const STATUS_LABELS: Record<EventStatus, string> = {
  draft: 'Draft',
  scheduled: 'Scheduled',
  cancelled: 'Cancelled',
  postponed: 'Postponed',
  soldOut: 'Sold out',
  completed: 'Past event',
};

export type { AnyImage };
